# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# https://www.d3data.de
#
# @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
# @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
# @link      https://www.oxidmodule.com

parameters:
  D3\LinkmobilityClient\ValueObject\Recipient.args.number:
  D3\LinkmobilityClient\ValueObject\Recipient.args.iso2countrycode:
  D3\LinkmobilityClient\ValueObject\Sender.args.number:
  D3\LinkmobilityClient\ValueObject\Sender.args.iso2countrycode:

services:
  _defaults:
    autowire: false
    public: true

  D3\LinkmobilityClient\LoggerHandler:
    class: D3\LinkmobilityClient\LoggerHandler
    factory:
      - 'D3\LinkmobilityClient\LoggerHandler'
      - 'getInstance'
    shared: true

  D3\LinkmobilityClient\ValueObject\Recipient:
    class: D3\LinkmobilityClient\ValueObject\Recipient
    factory: 'oxNew'
    shared: false
    arguments:
      - D3\LinkmobilityClient\ValueObject\Recipient
      - '%D3\LinkmobilityClient\ValueObject\Recipient.args.number%'
      - '%D3\LinkmobilityClient\ValueObject\Recipient.args.iso2countrycode%'

  D3\LinkmobilityClient\ValueObject\Sender:
    class: D3\LinkmobilityClient\ValueObject\Sender
    factory: 'oxNew'
    shared: false
    arguments:
      - D3\LinkmobilityClient\ValueObject\Sender
      - '%D3\LinkmobilityClient\ValueObject\Sender.args.number%'
      - '%D3\LinkmobilityClient\ValueObject\Sender.args.iso2countrycode%'

  D3\LinkmobilityClient\Exceptions\RecipientException:
    class: D3\LinkmobilityClient\Exceptions\RecipientException
    factory: 'oxNew'
    shared: false
    arguments:
      - D3\LinkmobilityClient\Exceptions\RecipientException