# This Software is the property of Data Development and is protected
# by copyright law - it is NOT Freeware.
#
# Any unauthorized use of this software without a valid license
# is a violation of the license agreement and will be prosecuted by
# civil and criminal law.
#
# https://www.d3data.de
#
# @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
# @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
# @link      https://www.oxidmodule.com

services:
  _defaults:
    autowire: false
    public: true

  # lang
  d3ox.linkmobility.OxidEsales\Eshop\Core\Language:
    class:      'OxidEsales\Eshop\Core\Session'
    factory:
      - 'OxidEsales\Eshop\Core\Registry'
      - 'getLang'
    shared:     true

  # UtilsView
  d3ox.linkmobility.OxidEsales\Eshop\Core\UtilsView:
    class:      'OxidEsales\Eshop\Core\UtilsView'
    factory:
      - 'OxidEsales\Eshop\Core\Registry'
      - 'get'
    arguments:
      - 'OxidEsales\Eshop\Core\UtilsView'
    shared:     true

  # Order
  d3ox.linkmobility.OxidEsales\Eshop\Application\Model\Order:
    class:      'OxidEsales\Eshop\Application\Model\Order'
    factory:    'oxNew'
    arguments:
      - 'OxidEsales\Eshop\Application\Model\Order'
    shared:     false

  # User
  d3ox.linkmobility.OxidEsales\Eshop\Application\Model\User:
    class:      'OxidEsales\Eshop\Application\Model\User'
    factory:    'oxNew'
    arguments:
      - 'OxidEsales\Eshop\Application\Model\User'
    shared:     false