# This Software is the property of Data Development and is protected
# by copyright law - it is NOT Freeware.
#
# Any unauthorized use of this software without a valid license
# is a violation of the license agreement and will be prosecuted by
# civil and criminal law.
#
# https://www.d3data.de
#
# @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
# @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
# @link      https://www.oxidmodule.com

parameters:
  d3ox.linkmobility.InvalidArgumentException.args.message:

services:
  _defaults:
    autowire: false
    public: true

  # InvalidArgumentException
  d3ox.linkmobility.InvalidArgumentException:
    class:      InvalidArgumentException
    factory:    'oxNew'
    arguments:
      - InvalidArgumentException
      - '%d3ox.linkmobility.InvalidArgumentException.args.message%'
    shared:     false